### PR TITLE
Docker Wizard manifest added

### PR DESCRIPTION
**Pull request by SergeyKemaev**
Adapted non-hierarchical PetClinic manifest added to be parsed by Docker Wizard
Part of https://github.com/qubell/vermilion/pull/6238

### CODE REVIEW

**Comment by SergeyKemaev** [comment]
@dmz please review

**Comment by SergeyKemaev** [comment]
@dornatsky @DmZ bump

**Comment by dornatsky** [comment]
don't call it "wizard", call it "simplified"

**Comment by SergeyKemaev** [comment]
wizard-petclinic.yml renamed to simplified-petclinic.yml

**Comment by dornatsky** [comment]
Please, note that you don't want to link a branch. Either refer to a specific commit, or a tag.

**Pull request merged**
