### PR TITLE
Annotate exposed port on tomcat

### PR DESCRIPTION
**Pull request by chemikadze**
Is required for ECS compatibility.

### CODE REVIEW

**Comment by rtimush** [comment]
@chemikadze Why do we need to fix a manifest here, not an ECS service?

**Comment by chemikadze** [comment]
@rtimush Unfortunately ECS does not exposes container port information that is not explicitly specified in ECS manifest, so there is no simple solution for this. Manifest workaround is a way easier.

**Comment by rtimush** [comment]
And we need this information because we do links manually, right?

**Comment by rtimush** [comment]
We should document this as a known limitation, if not already done

**Pull request merged**
